# Generated by Django 4.1.7 on 2023-07-02 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunApp', '0017_reservation_delete_preferedtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mail Adresi'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Adı'),
        ),
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Adı')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası')),
                ('rezervasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunApp.reservation', verbose_name='Rezervasyon Yapıldı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rezervasyonu Yapan Kişi')),
            ],
        ),
    ]
