# Generated by Django 4.1.7 on 2023-07-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0019_remove_reservation_date_makeappointment_resim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tel',
        ),
        migrations.AddField(
            model_name='reservation',
            name='aciklama',
            field=models.CharField(max_length=50, null=True, verbose_name='Aciklama'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='aciklama2',
            field=models.CharField(max_length=50, null=True, verbose_name='Aciklama2'),
        ),
    ]
