# Generated by Django 4.1.7 on 2023-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0020_remove_reservation_email_remove_reservation_tel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
