# Generated by Django 4.1.7 on 2023-07-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0023_alter_makeappointment_tel_alter_reservation_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeappointment',
            name='resim',
        ),
        migrations.RemoveField(
            model_name='makeappointment',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='makeappointment',
            name='title',
        ),
    ]
