# Generated by Django 4.1.7 on 2023-07-02 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0025_makeappointment_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeappointment',
            name='tel',
        ),
    ]
